<?php
$z[0]=Array("field","",35,63);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",65,94);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",156,176);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[3]=Array("channel","\r\n                        <p><a href=\"[field:typelink/]\">[field:typename/]</a> <span> > </span></p>\r\n                        ",204,382);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>