<?php
$z[0]=Array("field","",31,59);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",61,90);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",148,168);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[3]=Array("channel","\r\n                    <p><a href=\"[field:typelink/]\">[field:typename/]</a> <span> > </span></p>\r\n                    ",192,362);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>