<?php
$z[0]=Array("channelartlist","\r\n                <li>\r\n                    <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                    <div class=\"nav-son menu2\" id=\"slide{dede:field.typeid/}\">\r\n                        {dede:channel type='son' noself='yes'}\r\n                        <p><a href=\"[field:typelink/]\">[field:typename/]</a> <span> <img src=\"/images/zhnext.png\" alt=\"\"> <img src=\"/images/zhnext2.png\" class=\"hidden\" alt=\"\"> </span></p>\r\n                        {/dede:channel}\r\n                    </div>\r\n                </li>\r\n                ",774,1389);
$z[0][4]=array();
$z[0][4]['typeid']="top";
$z[1]=Array("channelartlist","\r\n            <li>\r\n                <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                <div class=\"nav-son menu2\" id=\"slide{dede:field.typeid/}\">\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <p><a href=\"[field:typelink/]\">[field:typename/]</a></p>\r\n                    {/dede:channel}\r\n                </div>\r\n            </li>\r\n            ",1671,2143);
$z[1][4]=array();
$z[1][4]['typeid']="top";

?>