<?php
$z[0]=Array("include","",75,110);
$z[0][4]=array();
$z[0][4]['filename']="meta.htm";
$z[1]=Array("global","",123,149);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",180,215);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("arclist","\r\n                        <div class=\"swiper-slide\">\r\n                            <a href=\"/plus/list.php?tid=4\"></a>\r\n                            <img src=\"[field:litpic/]\">\r\n                            <span class=\"czdq\"></span>\r\n                        </div>\r\n                        ",1592,1957);
$z[3][4]=array();
$z[3][4]['typeid']="4";
$z[3][4]['row']="4";
$z[3][4]['orderby']="hot";
$z[3][4]['channelid']="1";
$z[4]=Array("arclist","\r\n                        <div class=\"swiper-slide\">\r\n                            <a href=\"/plus/list.php?tid=4\"></a>\r\n                            <img src=\"[field:litpic/]\">\r\n                            <span class=\"czdq\"></span>\r\n                        </div>\r\n                        ",2610,2975);
$z[4][4]=array();
$z[4][4]['typeid']="5";
$z[4][4]['row']="4";
$z[4][4]['orderby']="hot";
$z[4][4]['channelid']="1";
$z[5]=Array("include","",3993,4030);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>