<?php
$z[0]=Array("include","",75,110);
$z[0][4]=array();
$z[0][4]['filename']="meta.htm";
$z[1]=Array("field","",123,145);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("global","",146,172);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",199,234);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("list","\r\n<div class=\"lixue\">\r\n    <!--<a href=\"\"></a>-->\r\n    <div class=\"margin\">\r\n        <div class=\"title\">\r\n            <h1>[field:title/]</h1>\r\n            <h2>[field:description/]</h2>\r\n        </div>\r\n        <div class=\"pic\">\r\n            <img src=\"[field:litpic/]\">\r\n            <span class=\"czdq\"></span>\r\n        </div>\r\n    </div>\r\n</div>\r\n",238,636);
$z[4][4]=array();
$z[4][4]['pagesize']="999";
$z[4][4]['orderby']="hot";
$z[5]=Array("include","",652,689);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>