<?php
$z[0]=Array("include","",75,110);
$z[0][4]=array();
$z[0][4]['filename']="meta.htm";
$z[1]=Array("global","",123,149);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",176,211);
$z[2][4]=array();
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n    <div class=\"lixue\">\r\n        <!--<a href=\"\"></a>-->\r\n        <div class=\"margin\">\r\n            <div class=\"title\">\r\n                <h1>[field:title/]</h1>\r\n                <h2>[field:description/]</h2>\r\n            </div>\r\n            <div class=\"pic\">\r\n                <img src=\"[field:litpic/]\">\r\n                <span class=\"czdq\"></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    ",242,696);
$z[3][4]=array();
$z[3][4]['pagesize']="999";
$z[3][4]['orderby']="hot";
$z[4]=Array("include","",710,747);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>